# Generated by Django 2.0.13 on 2019-05-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djinn_news', '0003_news_is_sticky'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description_feed',
            field=models.TextField(blank=True, help_text='Samenvatting specifiek voor tonen op infoscherm(en)', null=True, verbose_name='Infoscherm samenvatting'),
        ),
        migrations.AddField(
            model_name='news',
            name='publish_for_feed',
            field=models.BooleanField(default=False, help_text='Item tonen op infoscherm(en)', verbose_name='Toon op infoschermen'),
        ),
    ]
