# Generated by Django 2.0.13 on 2019-09-19 15:19

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djinn_news', '0004_auto_20190506_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='home_image_feed_crop',
            field=image_cropping.fields.ImageRatioField('home_image__image', '900x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='home image feed crop'),
        ),
    ]
