# Generated by Django 2.0.13 on 2019-10-15 11:37

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djinn_news', '0006_auto_20191003_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='use_default_image',
            field=models.BooleanField(default=False, help_text='Gebruik de afbeelding die voor dit content-type als standaardafbeelding is ingesteld.', verbose_name='Standaard afbeelding gebruiken'),
        ),
        migrations.AlterField(
            model_name='news',
            name='home_image_feed_crop',
            field=image_cropping.fields.ImageRatioField('home_image__image', '1920x1000', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text="Part of the home-image to use in the rss-feed. Upload or change home_image, click 'save and edit again' and then you can select a region to use in the rss feed.", hide_image_field=False, size_warning=True, verbose_name='Foto uitsnede'),
        ),
    ]
