# Generated by Django 2.0.13 on 2019-10-22 15:06

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djinn_contenttypes', '0001_initial'),
        ('djinn_news', '0007_auto_20191015_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='home_image_feed_crop',
        ),
        migrations.AddField(
            model_name='news',
            name='image_feed',
            field=models.ForeignKey(blank=True, help_text='Image for the rss-feed. Minimal width is 1920px, minimal heigt 500px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_image', to='djinn_contenttypes.ImgAttachment'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_feed_crop',
            field=image_cropping.fields.ImageRatioField('image_feed__image', '1920x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text="Part of the image_feed to use in the rss-feed. Upload or change home_image, click 'save and edit again' and then you can select a region to use in the rss feed.", hide_image_field=False, size_warning=True, verbose_name='Foto uitsnede'),
        ),
    ]
