# Generated by Django 2.0.13 on 2020-11-09 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djinn_contenttypes.models.publishable
import djinn_contenttypes.models.relatable
import djinn_contenttypes.models.sharing
import djinn_contenttypes.models.swappablemodel_mixin
import djinn_likes.models.likeable
import image_cropping.fields
import pgauth.base


class Migration(migrations.Migration):

    dependencies = [
        ('djinn_contenttypes', '0001_initial'),
        ('pgauth', '0003_auto_20201109_1559'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djinn_news', '0008_auto_20191022_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Changed')),
                ('removed_creator_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creator naam')),
                ('userkeywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Keywords')),
                ('is_tmp', models.BooleanField(default=False, verbose_name='Temporary')),
                ('publish_from', models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='Publish from')),
                ('publish_to', models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='Publish to')),
                ('publish_notified', models.BooleanField(default=False, help_text='Publish event is sent', verbose_name='Event sent')),
                ('unpublish_notified', models.BooleanField(default=False, help_text='Un-publish event is sent', verbose_name='Event sent')),
                ('remove_after_publish_to', models.BooleanField(default=False, verbose_name='Remove the content ater publication to has past')),
                ('comments_enabled', models.BooleanField(default=1, verbose_name="Collega's kunnen reageren")),
                ('publish_for_feed', models.BooleanField(default=False, help_text='Item tonen op infoscherm(en)', verbose_name='Toon op infoschermen')),
                ('use_default_image', models.BooleanField(default=False, help_text='Gebruik de afbeelding die voor dit content-type als standaardafbeelding is ingesteld.', verbose_name='Standaard afbeelding gebruiken')),
                ('description_feed', models.TextField(blank=True, help_text='Samenvatting specifiek voor tonen op infoscherm(en)', null=True, verbose_name='Infoscherm samenvatting')),
                ('text', models.TextField(blank=True, null=True)),
                ('image_feed_crop', image_cropping.fields.ImageRatioField('image_feed__image', '1920x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text="Part of the image_feed to use in the rss-feed. Upload or change home_image, click 'save and edit again' and then you can select a region to use in the rss feed.", hide_image_field=False, size_warning=True, verbose_name='Foto uitsnede')),
                ('show_images', models.BooleanField(default=True)),
                ('is_global', models.BooleanField(default=False)),
                ('is_sticky', models.BooleanField(default=False)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveblog_changed_by', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveblog_creator', to=settings.AUTH_USER_MODEL)),
                ('home_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveblog_home_image', to='djinn_contenttypes.ImgAttachment')),
                ('image_feed', models.ForeignKey(blank=True, help_text='Image for the rss-feed. Minimal width is 1920px, minimal heigt 500px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveblog_image', to='djinn_contenttypes.ImgAttachment')),
                ('parentusergroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveblog_parentusergroup', to='pgauth.UserGroup')),
            ],
            bases=(djinn_contenttypes.models.publishable.PublishableMixin, djinn_likes.models.likeable.LikeableMixin, models.Model, pgauth.base.LocalRoleMixin, djinn_contenttypes.models.sharing.SharingMixin, djinn_contenttypes.models.relatable.RelatableMixin, djinn_contenttypes.models.swappablemodel_mixin.SwappableModelMixin),
        ),
        migrations.CreateModel(
            name='LiveBlogUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Changed')),
                ('removed_creator_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creator naam')),
                ('userkeywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Keywords')),
                ('is_tmp', models.BooleanField(default=False, verbose_name='Temporary')),
                ('publish_from', models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='Publish from')),
                ('publish_to', models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='Publish to')),
                ('publish_notified', models.BooleanField(default=False, help_text='Publish event is sent', verbose_name='Event sent')),
                ('unpublish_notified', models.BooleanField(default=False, help_text='Un-publish event is sent', verbose_name='Event sent')),
                ('remove_after_publish_to', models.BooleanField(default=False, verbose_name='Remove the content ater publication to has past')),
                ('comments_enabled', models.BooleanField(default=1, verbose_name="Collega's kunnen reageren")),
                ('text', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveblogupdate_changed_by', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveblogupdate_creator', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(to='djinn_contenttypes.ImgAttachment')),
                ('liveblog', models.ForeignKey(help_text='The parent of this LiveBlog update', on_delete=django.db.models.deletion.CASCADE, to='djinn_news.LiveBlog', verbose_name='LiveBlog')),
                ('parentusergroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveblogupdate_parentusergroup', to='pgauth.UserGroup')),
            ],
            options={
                'abstract': False,
            },
            bases=(djinn_contenttypes.models.publishable.PublishableMixin, models.Model, pgauth.base.LocalRoleMixin, djinn_contenttypes.models.sharing.SharingMixin, djinn_contenttypes.models.relatable.RelatableMixin, djinn_contenttypes.models.swappablemodel_mixin.SwappableModelMixin, djinn_likes.models.likeable.LikeableMixin),
        ),
    ]
