# Generated by Django 2.0.13 on 2021-05-10 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djinn_news', '0009_liveblog_liveblogupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liveblogupdate',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='liveblogupdate',
            name='show_images',
            field=models.BooleanField(default=True, help_text='Toon de afbeelding(en) onderaan deze update', verbose_name='Afbeeldingen tonen'),
        ),
        migrations.AlterField(
            model_name='liveblogupdate',
            name='images',
            field=models.ManyToManyField(blank=True, to='djinn_contenttypes.ImgAttachment'),
        ),
        migrations.AlterField(
            model_name='liveblogupdate',
            name='liveblog',
            field=models.ForeignKey(help_text='The parent of this LiveBlog update', on_delete=django.db.models.deletion.CASCADE, related_name='liveblogupdates', to='djinn_news.LiveBlog', verbose_name='LiveBlog'),
        ),
    ]
