# Generated by Django 2.0.13 on 2021-11-22 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djinn_contenttypes', '0002_category'),
        ('djinn_news', '0010_auto_20210510_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, help_text='De categorie waaronder dit content-item verschijnt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_category', to='djinn_contenttypes.Category'),
        ),
    ]
