# Generated by Django 2.0.13 on 2022-05-24 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djinn_news', '0011_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='event_dt',
            field=models.DateTimeField(blank=True, default=None, help_text='Date/time of an event associated with this item.', null=True, verbose_name='Event date/time'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, help_text='De categorie waaronder dit content-item verschijnt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_category', to='djinn_contenttypes.Category', verbose_name='Category'),
        ),
    ]
